# 开始学习并测试cuda

In [1]:
import torch
print(torch.cuda.is_available())
torch.version.__version__

True


'2.0.1+cu118'

# 基本常识测试

In [3]:
# 生成一个6*4的0矩阵
A = torch.zeros(6, 4)
print(A)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
# 生成一个6*4均匀随机矩阵
B = torch.rand(6, 4)
print(B)       # 注意随机矩阵每次刷新生成结果都会不一样

tensor([[0.5235, 0.9180, 0.8760, 0.8235],
        [0.7577, 0.5396, 0.1096, 0.9080],
        [0.3327, 0.1300, 0.3039, 0.0740],
        [0.0786, 0.1658, 0.9320, 0.2650],
        [0.9540, 0.4197, 0.3018, 0.2270],
        [0.4086, 0.2787, 0.3308, 0.0029]])


In [5]:
# 生成一个3*6*4高斯随机数组
C = torch.randn(3, 6, 4)
print(C)

tensor([[[-0.0710, -0.2848, -1.0360,  0.1408],
         [-0.7641,  0.1686,  0.0895,  1.3284],
         [-1.4051,  0.9343,  0.4535, -1.4252],
         [ 1.4966, -0.7298, -0.1376, -0.2596],
         [-0.2085, -0.2545,  1.0301, -0.9938],
         [ 1.3350,  0.7056, -1.2472, -0.8449]],

        [[-0.6459,  0.9148,  0.7896,  0.2088],
         [-0.1468, -0.6042, -0.6629,  0.3512],
         [ 0.9237, -0.7059,  0.9575,  1.3783],
         [-0.6945, -0.1184,  1.0462, -0.9712],
         [ 0.7495,  2.1200, -0.3671, -1.1055],
         [ 0.0883, -1.1902, -0.7211, -2.2528]],

        [[-0.5258, -0.3549, -0.4089, -2.5850],
         [-0.6442, -0.8657, -0.7392, -0.7339],
         [-1.5654,  1.0170, -0.6202, -1.2822],
         [-0.8146, -1.0296,  0.4203,  1.7127],
         [-1.5226,  2.4463,  1.0782, -0.3357],
         [-1.2463,  0.2228,  1.2998,  1.6104]]])


In [8]:
# 定义一个5*3的空矩阵
torch.empty(5, 3)

tensor([[8.9082e-39, 8.9082e-39, 8.9082e-39],
        [1.0194e-38, 9.1837e-39, 4.6837e-39],
        [9.2755e-39, 1.0837e-38, 8.4490e-39],
        [9.9184e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39]])

In [9]:
# tensor()可以转化成array()
import torch
x_1 = torch.ones(5, 3)
x_2 = x_1.numpy()     # 注意这里的numpy()是torch里面的函数，不需要调用numpy库
x_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [10]:
# array()也可以转换成tensor()
import torch
x_3 = torch.from_numpy(x_2)
print(x_3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
import torch
import torch.nn as nn

# 创建一个输入大小为(3, 64, 64)的张量
input = torch.randn(100, 3, 64, 64)

# 创建一个二维卷积层
conv_layer = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1, padding=1)

# 将输入传递给卷积层
output = conv_layer(input)

# 输出结果的大小
print(output.size())

torch.Size([100, 16, 64, 64])


### 复现线性回归
- 准备数据

In [12]:
import numpy as np

x_values = [i for i in range(11)]     # 注意python可以使用这种方式写一个list
print(x_values)
x_train = np.array(x_values, dtype=np.float32)     # 注意dtype=np.float32不可省略
x_train = x_train.reshape(-1, 1)
print(x_train)
x_train.shape

y_values = [2*i+1 for i in x_values]     # 注意python可以使用这种方式写一个list
print(y_values)
y_train = np.array(y_values, dtype=np.float32)     # 注意dtype=np.float32不可省略
y_train = y_train.reshape(-1, 1)
print(y_train)
y_train.shape

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21]
[[ 1.]
 [ 3.]
 [ 5.]
 [ 7.]
 [ 9.]
 [11.]
 [13.]
 [15.]
 [17.]
 [19.]
 [21.]]


(11, 1)

- 构建模型

In [13]:
import torch
import torch.nn as nn
from tqdm import tqdm

class LinearRegressionModel(nn.Module):        # 继承父类nn.Module
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)    # 定义一个名为linear的类内对象
    
    def forward(self, x):                      # 复写父类函数——前向传播函数foward(self, ....)
        return self.linear(x)                  # 由于父类当中包含魔术方法__call__(self, ...),故可以在对象后面传入参数x

model = LinearRegressionModel(1, 1)            # 输入和输出维度均为1

if torch.cuda.is_available():
    print("device = gpu")
else:
    print("device = cpu")

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)

device = gpu


LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

- 设置模型参数

In [14]:
# 定义训练轮数
epochs = 1001

# 定义学习率(即每一轮优化的步长)
learning_rate = 0.01

# 定义一个对象optimizer，这是一个优化器，SGD表示随机梯度下降优化器，model.parameters()表示对model里面的全部参数进行优化
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)    

# 定义一个均方差损失函数
creterion = nn.MSELoss()

- 训练

In [18]:
# 使用tqdm库的tqdm模块去展示训练进程
for epoch in tqdm(range(epochs)):
    
    # 每一轮都让轮次+1
    epoch += 1

    # 更改输入数据类型
    inputs = torch.from_numpy(x_train).to(device)
    labels = torch.from_numpy(y_train).to(device)     # 将样本当中实际（绝对正确的）的y作为样本的labels
    
    # 设置可导
    inputs.requires_grad_()
    labels.requires_grad_()

    # 梯度要清零每一次迭代
    optimizer.zero_grad()
    
    # 前向传播
    outputs = model.forward(inputs)

    # 计算每一轮训练的损失,对比模型预测值outputs与正确的labels的之间的差异
    loss = creterion(outputs, labels)    

    # 反向传播,从数学上来说是对loss()的全部参数求导
    loss.backward()

    # 更新权重参数
    optimizer.step()

    # 每隔100轮训练输出一次
    if epoch == 1000:
        print(f"epoch={epoch},loss={loss.item()}")

100%|██████████| 1001/1001 [00:00<00:00, 1730.46it/s]

epoch=1000,loss=1.565551854820768e-11


- 测试模型预测结果

In [20]:
predicted = model(torch.from_numpy(x_train).requires_grad_().to(device))
print(f"正确结果{y_train}")
print(f"预测结果{predicted}")

正确结果[[ 1.]
 [ 3.]
 [ 5.]
 [ 7.]
 [ 9.]
 [11.]
 [13.]
 [15.]
 [17.]
 [19.]
 [21.]]
预测结果tensor([[ 1.0000],
        [ 3.0000],
        [ 5.0000],
        [ 7.0000],
        [ 9.0000],
        [11.0000],
        [13.0000],
        [15.0000],
        [17.0000],
        [19.0000],
        [21.0000]], device='cuda:0', grad_fn=<AddmmBackward0>)


- 保存模型

In [21]:
torch.save(model.state_dict(), "linear.pkl")     # 默认保存到当前文件夹下，也可以更改路径

"""
这段代码使用PyTorch中的`torch.save()`函数将模型的参数保存到文件中，文件名为'model.pkl'。

具体解释如下：
1 `torch.save()`: 这是PyTorch库中的一个函数,用于将Python对象保存到磁盘。它可以用来保存模型的参数、张量、字典等。
在这里，我们使用`torch.save()`函数来保存模型的参数。

2 `model.state_dict()`: 这是一个用于返回模型参数的方法。在PyTorch中,模型的参数通常存储在一个名为`state_dict`的字典中。
`model.state_dict()`用于获取模型的所有参数，并以字典的形式返回。

3 `'linear.pkl'`: 这是保存模型参数的文件名。在这个例子中，模型的参数将会保存到名为'model.pkl'的文件中。
综合起来，`torch.save(model.state_dict(), 'model.pkl')`这行代码的作用是将模型的参数保存到一个名为'model.pkl'的文件中，
以便在以后可以重新加载模型的参数，或者在其他地方使用这些参数进行推断或训练。通常，保存模型参数是为了在需要时可以方便地加载模型的状态，
避免重新训练模型，节省时间和资源。
"""

"\n这段代码使用PyTorch中的`torch.save()`函数将模型的参数保存到文件中，文件名为'model.pkl'。\n\n具体解释如下：\n1 `torch.save()`: 这是PyTorch库中的一个函数,用于将Python对象保存到磁盘。它可以用来保存模型的参数、张量、字典等。\n在这里，我们使用`torch.save()`函数来保存模型的参数。\n\n2 `model.state_dict()`: 这是一个用于返回模型参数的方法。在PyTorch中,模型的参数通常存储在一个名为`state_dict`的字典中。\n`model.state_dict()`用于获取模型的所有参数，并以字典的形式返回。\n\n3 `'linear.pkl'`: 这是保存模型参数的文件名。在这个例子中，模型的参数将会保存到名为'model.pkl'的文件中。\n综合起来，`torch.save(model.state_dict(), 'model.pkl')`这行代码的作用是将模型的参数保存到一个名为'model.pkl'的文件中，\n以便在以后可以重新加载模型的参数，或者在其他地方使用这些参数进行推断或训练。通常，保存模型参数是为了在需要时可以方便地加载模型的状态，\n避免重新训练模型，节省时间和资源。\n"

- 读取保存的模型

In [22]:
model.load_state_dict(torch.load("linear.pkl"))
"""
这段代码使用PyTorch中的`torch.load()`函数加载之前保存在文件中的模型参数，并使用`model.load_state_dict()`方法将加载的参数设置到模型中。

具体解释如下：
1 `torch.load('model.pkl')`: 这是PyTorch库中的一个函数，用于从磁盘加载保存的Python对象。
在这里，我们使用`torch.load()`函数从名为'model.pkl'的文件中加载模型的参数。这个文件之前是用`torch.save()`函数保存的模型参数。

2 `model.load_state_dict()`: 这是一个用于加载模型参数的方法。
在PyTorch中，模型的参数通常存储在一个名为`state_dict`的字典中。
`model.load_state_dict()`方法用于将加载的参数设置到模型中，使得模型的参数变成加载的参数。

3 综合起来，`model.load_state_dict(torch.load('model.pkl'))`这行代码的作用是从名为'model.pkl'的文件中加载之前保存的模型参数，
并将这些参数设置到`model`中，恢复模型的状态。这样，我们就可以继续使用这个模型进行推断、预测或训练，
而无需重新训练模型。这对于避免重新训练模型，节省时间和资源非常有用。
"""

"\n这段代码使用PyTorch中的`torch.load()`函数加载之前保存在文件中的模型参数，并使用`model.load_state_dict()`方法将加载的参数设置到模型中。\n\n具体解释如下：\n1 `torch.load('model.pkl')`: 这是PyTorch库中的一个函数，用于从磁盘加载保存的Python对象。\n在这里，我们使用`torch.load()`函数从名为'model.pkl'的文件中加载模型的参数。这个文件之前是用`torch.save()`函数保存的模型参数。\n\n2 `model.load_state_dict()`: 这是一个用于加载模型参数的方法。\n在PyTorch中，模型的参数通常存储在一个名为`state_dict`的字典中。\n`model.load_state_dict()`方法用于将加载的参数设置到模型中，使得模型的参数变成加载的参数。\n\n3 综合起来，`model.load_state_dict(torch.load('model.pkl'))`这行代码的作用是从名为'model.pkl'的文件中加载之前保存的模型参数，\n并将这些参数设置到`model`中，恢复模型的状态。这样，我们就可以继续使用这个模型进行推断、预测或训练，\n而无需重新训练模型。这对于避免重新训练模型，节省时间和资源非常有用。\n"

- 用保存好的训练模型预测新的数据

In [23]:
# 制造新的数据
x_value1 = [i for i in range(21, 41)]
x_test1 = np.array(x_value1, dtype=np.float32)
x_test1 = x_test1.reshape(-1, 1)
print(f"x_test = {x_test1}")
x_test1.shape

# 利用训练好的模型进行预测
predicted1 = model(torch.from_numpy(x_test1).requires_grad_().to(device))
print(f"预测结果为{predicted1}")

x_test = [[21.]
 [22.]
 [23.]
 [24.]
 [25.]
 [26.]
 [27.]
 [28.]
 [29.]
 [30.]
 [31.]
 [32.]
 [33.]
 [34.]
 [35.]
 [36.]
 [37.]
 [38.]
 [39.]
 [40.]]
预测结果为tensor([[43.0000],
        [45.0000],
        [47.0000],
        [49.0000],
        [51.0000],
        [53.0000],
        [55.0000],
        [57.0000],
        [59.0000],
        [61.0000],
        [63.0000],
        [65.0000],
        [67.0000],
        [69.0000],
        [71.0000],
        [73.0000],
        [75.0000],
        [77.0000],
        [79.0000],
        [81.0000]], device='cuda:0', grad_fn=<AddmmBackward0>)
