### 测试环境

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
torch.__version__

'2.0.1+cu118'

In [6]:
# 查看cuda的属性（变量）和方法（函数）
dir(torch.cuda)

['Any',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BoolStorage',
 'BoolTensor',
 'ByteStorage',
 'ByteTensor',
 'CUDAGraph',
 'CUDAPluggableAllocator',
 'CharStorage',
 'CharTensor',
 'ComplexDoubleStorage',
 'ComplexFloatStorage',
 'CudaError',
 'DeferredCudaCallError',
 'Device',
 'DoubleStorage',
 'DoubleTensor',
 'Event',
 'ExternalStream',
 'FloatStorage',
 'FloatTensor',
 'HalfStorage',
 'HalfTensor',
 'IntStorage',
 'IntTensor',
 'List',
 'LongStorage',
 'LongTensor',
 'Optional',
 'OutOfMemoryError',
 'ShortStorage',
 'ShortTensor',
 'Stream',
 'StreamContext',
 'Tuple',
 'Union',
 '_CudaBase',
 '_CudaDeviceProperties',
 '_DeviceGuard',
 '_LazySeedTracker',
 '__all__',
 '__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_check_capability',
 '_check_cubins',
 '_cudart',
 '_device',
 '_device_count_nvml',
 '_device_t',
 '_dummy_type',
 '_exchange_device',
 '_get_device_index',
 '_initia

In [4]:
# 查看GPU数量
torch.cuda.device_count()

1

In [5]:
# 查看当前GPU序号 
torch.cuda.current_device()

0

In [8]:
# 查看GPU详细型号，输入要查的GPU型号
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3050 Ti Laptop GPU'

In [7]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# 高斯随机分布的二维张量
b = torch.randn(4, 4)
b

tensor([[ 0.2267, -1.2464,  0.6364, -1.2393],
        [-0.3480, -0.0792, -0.8374, -0.2874],
        [-1.0666, -1.0328, -0.8544, -0.5399],
        [ 1.0383,  1.8177,  0.4158, -0.1728]])

In [9]:
c = torch.rand(4, 4)
c

tensor([[0.2783, 0.8520, 0.4123, 0.8914],
        [0.8886, 0.2220, 0.6906, 0.1864],
        [0.0119, 0.8056, 0.6161, 0.4236],
        [0.1252, 0.2172, 0.6698, 0.6132]])

In [10]:
d = a + b + c
d

tensor([[ 1.5049,  0.6056,  2.0487,  0.6521],
        [ 1.5406,  1.1428,  0.8531,  0.8990],
        [-0.0547,  0.7728,  0.7617,  0.8838],
        [ 2.1635,  3.0349,  2.0856,  1.4404]])

In [11]:
# 把数据导到GPU上
a = a.to("cuda:0")
b = b.to("cuda:0")
c = c.to("cuda:0")
d = d.to("cuda:0")
print(f"a = {a}")
print(f"b = {b}")
print(f"c = {c}")
print(f"d = {d}")

a = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
b = tensor([[ 0.2267, -1.2464,  0.6364, -1.2393],
        [-0.3480, -0.0792, -0.8374, -0.2874],
        [-1.0666, -1.0328, -0.8544, -0.5399],
        [ 1.0383,  1.8177,  0.4158, -0.1728]], device='cuda:0')
c = tensor([[0.2783, 0.8520, 0.4123, 0.8914],
        [0.8886, 0.2220, 0.6906, 0.1864],
        [0.0119, 0.8056, 0.6161, 0.4236],
        [0.1252, 0.2172, 0.6698, 0.6132]], device='cuda:0')
d = tensor([[ 1.5049,  0.6056,  2.0487,  0.6521],
        [ 1.5406,  1.1428,  0.8531,  0.8990],
        [-0.0547,  0.7728,  0.7617,  0.8838],
        [ 2.1635,  3.0349,  2.0856,  1.4404]], device='cuda:0')
